item {
  id: 1
  name: 'Knife'
}
item {
  id: 2
  name: 'Spoon'
}
item {
  id: 1
  name: 'banana'
}
item {
  id: 1
  name: 'Apple'
}
item {
  id: 1
  name: 'Orange'
}
item {
  id: 1
  name: 'Broccoli'
}
item {
  id: 1
  name: 'Carot'
}
item {
  id: 1
  name: 'Pizza'
}
item {
  id: 1
  name: 'Cake'
}
item {
  id: 1
  name: 'Chair'
}
item {
  id: 1
  name: 'Sofa'
}
item {
  id: 1
  name: 'Bed'
}item {
  id: 1
  name: 'Diningtable'
}
item {
  id: 1
  name: 'Toilet'
}
item {
  id: 1
  name: 'TV '
}
item {
  id: 1
  name: 'Laptop'
}
item {
  id: 1
  name: 'Mouse'
}
item {
  id: 1
  name: 'Remote'
}
item {
  id: 1
  name: 'Keyboard'
}
item {
  id: 1
  name: 'Phone'
}
item {
  id: 1
  name: 'Microwave'
}
item {
  id: 1
  name: 'Oven'
}
item {
  id: 1
  name: 'Toaster'
}
item {
  id: 1
  name: 'Sink'
}
item {
  id: 1
  name: 'Refrigerator'
}
item {
  id: 1
  name: 'Book'
}
item {
  id: 1
  name: 'Clock'
}
item {
  id: 1
  name: 'Vase'
}
item {
  id: 1
  name: 'Scissor'
}
item {
  id: 1
  name: 'Teddy bear'
}
item {
  id: 1
  name: 'Hair drier'
}
item {
  id: 1
  name: 'Tooth brush'
}
item {
  id: 1
  name: 'Truck'
}
item {
  id: 1
  name: 'Bicycle'
}
item {
  id: 1
  name: 'Train'
}
item {
  id: 1
  name: 'Fan'
}
item {
  id: 1
  name: 'Bus'
}
